---
# tasks file for pleasanter-centos
- name: "Linux Software Repository for Microsoft Products"
  yum:
    name: "{{ packages_microsoft_com }}"
    state: latest

- name: "install .NetCORE 2.2"
  yum:
    name: dotnet-sdk-2.2
    state: present

- include_role:
    name: geerlingguy.git
    public: yes

- include_role:
    name: onegreyonewhite.package_installer
    public: yes
