---
# tasks file for pleasanter-centos
- include_role:
    name: arillso.repositories
    public: yes

- include_role:
    name: geerlingguy.git
    public: yes

- include_role:
    name: onegreyonewhite.package_installer
    public: yes
