---
# tasks file for pleasanter-centos
- include_role:
    name: robertdebock.selinux
  vars:
    selinux_state: disabled
  tags:
    - selinux

- name: "Add msprod repository"
  shell: yum-config-manager --add-repo={{ msprod_repo }}
  tags:
    - dotnet
    - mssql

- name: "Add mssql-server repository"
  shell: yum-config-manager --add-repo={{ mssql_server_repo}}
  tags:
    - mssql

- name: "install .NetCORE 2.2"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dotnet-sdk-2.2
  tags:
    - dotnet

- name: "install mssql-server 2017"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-server
  tags:
    - mssql

- name: "stop service mssql-server on debian, if running"
  systemd:
    name: mssql-server
    state: stopped
  ignore_errors: True
  tags:
    - mssql

- name: "mssql-server unattended-install"
  shell: |
    MSSQL_SA_PASSWORD='{{ mssql_sa_password }}'
    MSSQL_PID='{{ mssql_pid }}'
    MSSQL_LCID='{{ mssql_lcid }}'
    if [ -z $MSSQL_SA_PASSWORD ]
    then
      echo Environment variable MSSQL_SA_PASSWORD must be set for unattended install
      exit 1
    fi
    echo Running mssql-conf setup...
    sudo MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD MSSQL_PID=$MSSQL_PID MSSQL_LCID=$MSSQL_LCID /opt/mssql/bin/mssql-conf -n setup accept-eula
  tags:
    - mssql

- name: "remove mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
      - unixODBC-utf16
      - unixODBC-utf16-devel
  tags:
    - mssql

- name: "install mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
  environment:
    ACCEPT_EULA: "Y"
  tags:
    - mssql

- name: "install mssql GDI"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libgdiplus
  tags:
    - mssql

- include_role:
    name: geerlingguy.git
    public: yes
  tags:
    - pleasanter

- name: "clone Pleasanter"
  git:
    repo: https://github.com/Implem/Implem.Pleasanter.NetCore.git
    dest: /Pleasanter
  tags:
    - pleasanter

- name: "Run build script"
  shell: "sh build.sh"
  args:
    chdir: /Pleasanter/cmdnetcore
  tags:
    - pleasanter
    - pleasanter_build

- name: "setup conf file"
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: Rds.json.j2
      dest: /Pleasanter/publish/Implem.Pleasanter/App_Data/Parameters/Rds.json
  tags:
    - pleasanter
    - pleasanter_build

- name: "Run build codedefiner script"
  shell: "sh codedefiner.sh"
  args:
    chdir: /Pleasanter/cmdnetcore
  tags:
    - pleasanter
    - pleasanter_build
    - pleasanter_db
