---
# tasks file for pleasanter-centos
- include_role:
    name: geerlingguy.git
    public: yes

# - include_role:
#     name: onegreyonewhite.package_installer
#     public: yes

- name: "Add msprod repository"
  shell: yum-config-manager --add-repo={{ msprod_repo }}

- name: "Add mssql-server repository"
  shell: yum-config-manager --add-repo={{ mssql_server_repo}}

- name: "install .NetCORE 2.2"
  yum:
    name: dotnet-sdk-2.2
    state: present

- name: "install mssql-server 2017"
  yum:
    name: mssql-server
    state: present

- name: "stop service mssql-server on debian, if running"
  systemd:
    name: mssql-server
    state: stopped
  ignore_errors: True

- name: "mssql-server unattended-install"
  shell: |
    MSSQL_SA_PASSWORD='{{ mssql_sa_password }}'
    MSSQL_PID='{{ mssql_pid }}'
    SQL_ENABLE_AGENT='y'
    if [ -z $MSSQL_SA_PASSWORD ]
    then
      echo Environment variable MSSQL_SA_PASSWORD must be set for unattended install
      exit 1
    fi
    echo Running mssql-conf setup...
    sudo MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD MSSQL_PID=$MSSQL_PID /opt/mssql/bin/mssql-conf -n setup accept-eula

- name: "remove mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
      - unixODBC-utf16
      - unixODBC-utf16-devel

- name: "install mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
  environment:
    ACCEPT_EULA: "Y"

- name: "install mssql GDI"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libgdiplus

