---
# tasks file for pleasanter-centos
- name: "Add msprod repository"
  shell: yum-config-manager --add-repo={{ msprod_repo }}
  tags:
    - dotnet
    - mssql

- name: "Add mssql-server repository"
  shell: yum-config-manager --add-repo={{ mssql_server_repo}}
  tags:
    - mssql

- name: "install .NetCORE 2.2"
  yum:
    name: dotnet-sdk-2.2
    state: present
  tags:
    - dotnet

- name: "install mssql-server 2017"
  yum:
    name: mssql-server
    state: present
  tags:
    - mssql

- name: "stop service mssql-server on debian, if running"
  systemd:
    name: mssql-server
    state: stopped
  ignore_errors: True
  tags:
    - mssql

- name: "mssql-server unattended-install"
  shell: |
    MSSQL_SA_PASSWORD='{{ mssql_sa_password }}'
    MSSQL_PID='{{ mssql_pid }}'
    SQL_ENABLE_AGENT='y'
    if [ -z $MSSQL_SA_PASSWORD ]
    then
      echo Environment variable MSSQL_SA_PASSWORD must be set for unattended install
      exit 1
    fi
    echo Running mssql-conf setup...
    sudo MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD MSSQL_PID=$MSSQL_PID /opt/mssql/bin/mssql-conf -n setup accept-eula
  tags:
    - mssql

- name: "remove mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
      - unixODBC-utf16
      - unixODBC-utf16-devel
  tags:
    - mssql

- name: "install mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
  environment:
    ACCEPT_EULA: "Y"
  tags:
    - mssql

- name: "install mssql GDI"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libgdiplus
  tags:
    - mssql

- include_role:
    name: geerlingguy.git
    public: yes
  tags:
    - pleasanter

- name: "clone Pleasanter"
  git:
    repo: https://github.com/Implem/Implem.Pleasanter.NetCore.git
    dest: /Pleasanter
  tags:
    - pleasanter

- name: "Run build script"
  shell: /Pleasanter/cmdnetcore/build.sh
  tags:
    - pleasanter
    - pleasanter_build
