---
# tasks file for pleasanter-centos

- name: "Add msprod repository"
  shell: yum-config-manager --add-repo={{ msprod_repo }}
  tags:
    - dotnet
    - mssql

- name: "Add mssql-server repository"
  shell: yum-config-manager --add-repo={{ mssql_server_repo}}
  tags:
    - mssql

- name: "install .NetCORE 2.2"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dotnet-sdk-2.2
  tags:
    - dotnet

- name: "install mssql-server 2017"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-server
  tags:
    - mssql

- name: "stop service mssql-server on debian, if running"
  systemd:
    name: mssql-server
    state: stopped
  ignore_errors: True
  tags:
    - mssql

- name: "mssql-server unattended-install"
  shell: |
    MSSQL_SA_PASSWORD='{{ mssql_sa_password }}'
    MSSQL_PID='{{ mssql_pid }}'
    MSSQL_LCID='{{ mssql_lcid }}'
    if [ -z $MSSQL_SA_PASSWORD ]
    then
      echo Environment variable MSSQL_SA_PASSWORD must be set for unattended install
      exit 1
    fi
    echo Running mssql-conf setup...
    sudo MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD MSSQL_PID=$MSSQL_PID MSSQL_LCID=$MSSQL_LCID /opt/mssql/bin/mssql-conf -n setup accept-eula
  tags:
    - mssql

- name: "remove mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
      - unixODBC-utf16
      - unixODBC-utf16-devel
  tags:
    - mssql

- name: "install mssql-tools and unixODBC developer"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mssql-tools
      - unixODBC-devel
  environment:
    ACCEPT_EULA: "Y"
  tags:
    - mssql

- name: "install mssql GDI"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libgdiplus
  tags:
    - mssql

- name: "install git"
  include_role:
    name: geerlingguy.git
    public: yes
    apply:
      tags:
        - pleasanter
  tags:
    - pleasanter

- name: "clone Pleasanter"
  git:
    repo: https://github.com/Implem/Implem.Pleasanter.NetCore.git
    dest: /Pleasanter
  tags:
    - pleasanter

- name: "Run pleasanter build script"
  shell: "sh build.sh"
  args:
    chdir: /Pleasanter/cmdnetcore
  tags:
    - pleasanter
    - pleasanter_build

- name: "setup pleasanter conf file"
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: Rds.json.j2
      dest: /Pleasanter/publish/Implem.Pleasanter/App_Data/Parameters/Rds.json
    - src: Mail.json.j2
      dest: /Pleasanter/publish/Implem.Pleasanter/App_Data/Parameters/Mail.json
  notify: restart pleasanter
  tags:
    - pleasanter
    - pleasanter_build
    - pleasanter_conf

- name: "Run build codedefiner script"
  shell: "sh codedefiner.sh"
  args:
    chdir: /Pleasanter/cmdnetcore
  tags:
    - pleasanter
    - pleasanter_build
    - pleasanter_db

- name: "pleasanter service"
  include_role:
    name: 0x0i.systemd
    apply:
      tags:
        - pleasanter
        - pleasanter_build
        - systemd
  vars:
    unit_config:
      - name: "pleasanter"
        Unit:
          Description: "Pleasanter"
          Documentation: ""
          Wants: network.target
          After: network.target
        Service:
          ExecStart: "/usr/bin/dotnet Implem.Pleasanter.NetCore.dll --urls=http://localhost:5000 --pathbase=/pleasanter"
          WorkingDirectory: "/Pleasanter/publish/Implem.Pleasanter/"
          Restart: always
          RestartSec: 10
          User: root
          Group: root
          Environment: "ASPNETCORE_ENVIRONMENT=Production"
        Install:
          WantedBy: multi-user.target
  tags:
    - pleasanter
    - pleasanter_build
    - systemd

- name: "install nginx"
  include_role:
    name: geerlingguy.nginx
    apply:
      tags:
        - nginx
  vars:
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "{{ server_name }}"
        extra_parameters: |
          location / {
            proxy_pass http://localhost:5000;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
          }
  tags:
    - nginx

- name: "setup firewall"
  include_role:
    name: geerlingguy.firewall
    apply:
      tags:
        - firewall
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
  tags:
    - firewall
